---
title: "Extension"
author: "Maria Burzillo"
date: "4/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
knitr::write_bib(c("knitr", "stringr"), "bib.bib", width = 60)
library(haven)
library(gtable)
library(stargazer)
library(tidyverse)
library(gt)
library(gtsummary)
library(knitr)
library(stargazer)
library(lme4)
library(margins)
library(reprex)
library(plm)
library(devtools)
library(lfe)
library(Statamarkdown)
library(readxl)
library(starpolishr)
library(AER)
library(readxl)
library(naniar)
library(mice)
```

```{r data_imports, include = FALSE}

# import both datasets

rp <- read_dta("racial_polarization_winners.dta")
fin_seg<- read_dta("fin_seg.dta")

```

# Main Analysis

```{r include = FALSE}

rp_vars <- c("winner", "medincinterp",
             "biggestsplit", "H_citytract_multi_i", "diversityinterp",
             "pctasianpopinterp", "pctblkpopinterp", "pctlatinopopinterp",
             "pctrentersinterp", "pctcollegegradinterp", "biracial", "nonpartisan",
             "primary", "logpop", "year", "south", "midwest", "west", "geo_id2",
             "H_citytract_NHW_i", "whiteideology_fill2"
             )

rp_impute <- rp %>%
  select("winner", "medincinterp",
             "biggestsplit", "H_citytract_multi_i", "diversityinterp",
             "pctasianpopinterp", "pctblkpopinterp", "pctlatinopopinterp",
             "pctrentersinterp", "pctcollegegradinterp", "biracial", "nonpartisan",
             "primary", "logpop", "year", "south", "midwest", "west", "geo_id2",
             "H_citytract_NHW_i", "whiteideology_fill2") %>%
  filter(winner == 1)%>%
  mutate(medincinterp = medincinterp/1000,
         year.f = as.factor(year))


nrow(rp_impute)

```



```{r exploring_missing_values, echo = FALSE}


miss_var_summary(rp_impute)

gg_miss_var(rp_impute)

gg_miss_var(rp_impute, show_pct = TRUE)

```

```{r imputation_for_rp_dataset}

imp_1_rp <- mice(rp_impute, maxit = 0)

pred <- imp_1_rp$predictorMatrix

methods_1 <- imp_1_rp$method

methods_1["medincinterp"] <- "cart"
methods_1["biggestsplit"] <- "cart"

imp_1_rp <- mice(rp_impute, maxit = 1, method = methods_1)

# multiple imputations using the cart method

view(rp_impute)

imp_1_rp <- mice(rp_impute, method = "cart", maxit = 3)

write.csv(complete(imp_1_rp), "imp_1_rp.csv")

gg_miss_var(complete(imp_1_rp), show_pct = TRUE)

```

```{r, results="asis", echo = FALSE}
# fit multiple imputed datasets

fit_imp_1_rp <- with(imp_1_rp, lmer(biggestsplit ~ H_citytract_multi_i + diversityinterp + pctasianpopinterp + pctblkpopinterp + pctlatinopopinterp + medincinterp + pctrentersinterp +  pctcollegegradinterp + biracial + nonpartisan + primary + logpop + year.f + south + midwest + west + (1 | geo_id2), REML=FALSE))

# pool the analyses

pool_imp_1_rp <- pool(fit_imp_1_rp)
imp_1_rp_sum <- summary(pool_imp_1_rp)


# look at the table
gt(imp_1_rp_sum)

stargazer(imp_1_rp_sum)


imp_1_rp$method

```


```{r}
miss_var_summary(fin_seg)

fin_seg$citypop

gg_miss_var(rp_impute)

gg_miss_var(rp_impute, show_pct = TRUE, facet = year)
```

```{r}

# basic filter for table for all regressions

fin_imp_1 <-fin_seg %>%
  select(totaltractsf,dgepercap_cpi, H_citytract_NHW_i, diversityinterp,
         pctblkpopinterp, pctasianpopinterp, pctlatinopopinterp, medinc_cpi,
         pctlocalgovworker_100, pctrentersinterp, pctover65,
         pctcollegegradinterp, logpop, highwayspercapNC_cpi, parkspercapNC_cpi,
         policepercapNC_cpi, sewerspercapNC_cpi, welfhoushealthNC_cpi,
         genrevownpercap_cpi, H_citytract_multi_i, diversityinterp, pctblkpopinterp, pctasianpopinterp, pctlatinopopinterp, chng5pctblk, chng5pctlatino, chng5pctasian,medinc_cpi, pctlocalgovworker_100, pctrentersinterp, pctover65, pctcollegegradinterp, logpop, ideology_fill, population, geo_id2)

miss_var_summary(fin_imp_1)

#felm1 <- felm(dgepercap_cpi ~ H_citytract_NHW_i + diversityinterp + pctblkpopinterp + pctasianpopinterp + pctlatinopopinterp + medinc_cpi + pctlocalgovworker_100 + pctrentersinterp + pctover65 + pctcollegegradinterp + logpop | factor(geo_id2) |0| geo_id2, data = fin_seg_sub)

fin_imp <- fin_imp_1 %>%
  select(H_citytract_NHW_i, dgepercap_cpi, diversityinterp, pctblkpopinterp, pctasianpopinterp,
         pctlatinopopinterp, medinc_cpi, pctlocalgovworker_100, pctrentersinterp, pctover65,
         pctcollegegradinterp, logpop, geo_id2)

miss_var_summary(fin_imp)


```


```{r}
ini <- mice(fin_imp, maxit=0, print=F)

meth <- ini$method

meth[c("dgepercap_cpi", "diversityinterp", "pctblkpopinterp", "pctasianpopinterp",
         "pctlatinopopinterp", "medinc_cpi", "pctlocalgovworker_100", "pctrentersinterp",
         "pctover65", "pctcollegegradinterp", "logpop", "geo_id2")]=""

meth[c("H_citytract_NHW_i")] = "cart"

imp_1_fs <- mice(fin_imp, method = meth, maxit = 1)

miss_var_summary(complete(imp_1_fs,3))



```

```{r}
fin_seg_sub <- fin_seg %>%
  filter(totaltractsf > 1 | is.na(totaltractsf), dgepercap_cpi != 0 | is.na(dgepercap_cpi)) %>%
  mutate(medinc_cpi = medinc_cpi/1000)

fin_imp <- fin_seg_sub %>%
  select(H_citytract_NHW_i, dgepercap_cpi, diversityinterp, pctblkpopinterp, pctasianpopinterp, pctlatinopopinterp, medinc_cpi, pctlocalgovworker_100, pctrentersinterp,  pctover65, pctcollegegradinterp, logpop, geo_id2)


#felm1 <- felm(dgepercap_cpi ~ H_citytract_NHW_i + diversityinterp + pctblkpopinterp + pctasianpopinterp + pctlatinopopinterp + medinc_cpi + pctlocalgovworker_100 + pctrentersinterp + pctover65 + pctcollegegradinterp + logpop | factor(geo_id2) |0| geo_id2, data = fin_seg_sub)

ini <- mice(fin_imp, maxit=0, print=F)

pred_matrix <- ini$pred

meth <- ini$method

others <- c("medinc_cpi")

meth[c("pctasianpopinterp", "pctlatinopopinterp", "pctblkpopinterp","pctlocalgovworker_100", "pctover65", "pctcollegegradinterp", 
                    "logpop")]=""

meth[c("dgepercap_cpi", "H_citytract_NHW_i", "medinc_cpi", "pctrentersinterp", "diversityinterp")] = "cart"

#meth[c("medinc_cpi")] = "pmm"

#new_pred_matrix <- pred_matrix[,1:2]

try2 <- mice(fin_imp, maxit=1, method = meth)

pred_matrix[,]

view(complete(try2))

nrow(complete(try2))

sum(is.na(complete(try2)$dgepercap_cpi))
sum(is.na(fin_imp$dgepercap_cpi))

miss_var_summary(fin_imp)

miss_var_summary(complete(try2))


felm1_imp <- with(try2, felm(dgepercap_cpi ~ H_citytract_NHW_i + diversityinterp + pctblkpopinterp + pctasianpopinterp + pctlatinopopinterp + medinc_cpi + pctlocalgovworker_100 + pctrentersinterp + pctover65 + pctcollegegradinterp + logpop | factor(geo_id2) |0| geo_id2, data = fin_seg_sub))

pool_felm1_imp<- pool(felm1_imp)
felm1_imp_sum <- summary(pool_felm1_imp)


print(felm1_imp_sum, digits = 3)
```

```{r}
ini <- mice(fin_imp, maxit=0, print=F)

pred_matrix <- ini$pred

meth <- ini$method

try3 <- mice(fin_imp, maxit=1, method = "cart")

```

```{r}

ini <- mice(fin_imp, maxit=0, print=F)

pred_matrix <- ini$pred

meth <- ini$method

meth[c("pctlocalgovworker_100", "pctover65", "pctcollegegradinterp", 
                    "logpop")]=""

meth[c("pctasianpopinterp", "pctlatinopopinterp", "pctblkpopinterp","dgepercap_cpi", "H_citytract_NHW_i", "medinc_cpi", "pctrentersinterp", "diversityinterp")] = "cart"

try4 <- mice(fin_imp, maxit=1, method = meth)


```

```{r}

ini <- mice(fin_imp, maxit=0, print=F)

pred_matrix <- ini$pred

meth <- ini$method

meth[c("pctcollegegradinterp", 
                    "logpop")]=""

meth[c("pctasianpopinterp", "pctlatinopopinterp", "pctblkpopinterp","dgepercap_cpi", "H_citytract_NHW_i", "medinc_cpi", "pctrentersinterp", "diversityinterp", "pctlocalgovworker_100", "pctover65")] = "cart"

try5 <- mice(fin_imp, maxit=1, method = meth)


```

```{r}

ini <- mice(fin_imp, maxit=0, print=F)

pred_matrix <- ini$pred

meth <- ini$method

meth[c("logpop")]=""

meth[c("pctasianpopinterp", "pctlatinopopinterp", "pctblkpopinterp","dgepercap_cpi", "H_citytract_NHW_i", "medinc_cpi", "pctrentersinterp", "diversityinterp", "pctlocalgovworker_100", "pctover65", "pctcollegegradinterp")] = "cart"

try5 <- mice(fin_imp, maxit=1)

try7 <- mice(fin_imp, maxit = 1, method = "cart")

write.csv(try6, "try6_1_imp.csv")

try6.2 <- mice(fin_imp, maxit = 3, method = "cart")

write.csv(try6.2, "try6_3_imp.csv")


write.csv(complete(try7), "try7.csv")


```

