---
title: "Writing Draft"
author: "Maria Burzillo"
date: "3/28/2020"
output: 
  pdf_document:
    extra_dependencies: ["rotating"]
bibliography: final_proj_bib.bib
#biblio-style: "apalike"
link_citations: true
header_includes:
  - \usepackage{float}
  - \usepackage{dcolumn}
  - \usepackage{rotating}
  
---

# Abstract

@trounstine_segregation_2016 suggests that high levels of residential segregation are associated with increased political polarization and decreased public spending. In this analysis, I was able to successfully replicate @trounstine_segregation_2016’s main results. Adding onto her original analysis, I impute a large amount of missing data from the original dataset and re-run the analysis. Finally, I add in income segregation as a predictor in her regressions to assess whether this could be a confounding variable. 

# Introduction

There is a large degree of variation in public goods spending across local governments. As a result, many scholars have worked to determine what factors may lead to the underprovision of public goods spending. Some scholars in the past have associated racial diversity or changes in levels of diversity with the under-provision of public goods [@baqir_public_1999; @hopkins_diversity_2009].  However, @trounstine_segregation_2016 argues that it is racial segregation, not diversity in and of itself, that results in the under-provision of public goods. Trounstine’s analysis consists of two main parts. First, she uses election and demographic data from 25 of America’s largest cities between 1990 and 2010 to run a multilevel mixed-effects linear regression with fixed effects for region and year and with random effects for cities in order to show that polarization increases with segregation. Trounstine measures segregation with Theil's H index, which measures the degree to which the diversity of a neighborhood differs from the diversity of the entire city. The second main part of Trounstine’s analysis looks at the ability of the Theil’s H segregation index to explain a variety of types of public expenditures by city using a sample of 2,637 cities with 13,742 city-year observations. Using linear regressions with fixed effects for cities and robust standard errors clustered by city, Trounstine finds a significant, negative correlation between segregation and public goods spending that is robust to the inclusion of a variety of relevant controls and an alternative specification in which the number of waterways is used as an instrument for segregation. 

In this analysis, I first work to replicate the main results of @trounstine_segregation_2016 using R statistical software [@r]. The original data and Stata code made publically available by the author were downloaded via the Harvard Dataverse [@DVN/4LZXTY_2015]. I also make all of my code and analysis available on Github.^[ Link to my [Github repository](https://github.com/mburzillo/new_final_project) for this project.] I was successfully able to replicate the main results of @trounstine_segregation_2016 in R with the exception of some of the marginal analyses, which I was nevertheless able to replicate in Stata. 

```{r setup, include = FALSE}

# import both datasets
library(haven)
rp <- read_dta("racial_polarization_winners.dta")
fin_seg<- read_dta("fin_seg.dta")

# calculate number of original observations
obs_fin_seg <- nrow(fin_seg)
obs_rp <- nrow(rp)

```


One concern with the original analysis in @trounstine_segregation_2016 is the large amount of missing data, which substantially constrains the sample size used in the regression analysis. For example, the regression analysis in the main specification using the the original racial polarization exludes %`r (obs_rp - 91)/obs_rp` of the observations in the original dataset, and the regression analysis in the main specification using the original financial segregation data excludes %`r (obs_fin_seg - 13742)/ obs_fin_seg` of observations from the original dataset. As an extension of @trounstine_segregation_2016, I impute missing values in the original data using the mice package in R, which generates multivariate imputations using chained equations [@mice]. Then, I use the imputed datasets to re-estimate the original models, pooling the results to final pooled regression coefficients and parameters. 

Comparing the results of the original regressions and those done with the imputed data yields similar big picture results in terms of the direction of the signs on the coefficients on the segregation indices. Like in @trounstine_segregation_2016, I find that segregation is positively associated with political polarization and negatively associated with spending on public goods. However, the magnitude of the effects in most specifications has dminished and most results become statistically insignificant. While these findings do not necessarily challenge the results of @trounstine_segregation_2016, they do call into question the relative importance of segregation in determining public goods spending and political polarization and suggest that the results of @trounstine_segregation_2016 may not be quite as robust as once thought. 



# Literature Review

Despite some progress made towards racial equity in the U.S. on other fronts, residential racial segregation in U.S. neighborhoods continues to be prevasive and deeply entrenched in society [@fischer_distinguishing_2004; @oliver_paradoxes_2010; @massey_american_1993]. Research suggests that this kind of segregation has political consequences, as political cleavages in segregated cities tend to have racial as well as spatial dimensions [@massey_american_1993]. Neighborhoods are often important actors within local politics because local governments provide many functions that are allocational in nature and concern geographical space [@trounstine_segregation_2016]. Thus, when neighborhoods are divided on racial lines as well as spacial lines, it is natural to expect higher degrees of racial polarization as a result. 


Studying residential segregation is difficult because its effects tend to differ by geographic level. On the neighborhood level, the kind of geographic racial isolation brought on by residential segregation has been associated with racial intolerance, resentment, and competition between racial groups [@oliver_paradoxes_2010]. Living within segregated neighborhoods has also been associated with holding negative stereotypes and perceptions about out groups [@eric_oliver_intergroup_2003]. As a result, homogeneous neighborhoods have been associated with increased racial tension and political polarization in comparison to integrated, diverse neighborhoods. However, at the city or metropolitan level, the opposite seems to be true: when considering larger geographic areas, diversity and integration are correlated with racial tension, competition, prejudice, lower levels of cooperation, and lower spending on public goods [@oliver_paradoxes_2010; @baqir_public_1999; @hopkins_diversity_2009]. While these differences in the expected effect of segregation on the geographic level may seem confusing at first, they make sense as they suggest that the most severely segregated area is one that is diverse overall, but has many homogeneous neighborhoods. Thus, while people of different races co-exist within a highly segregated city, they live separately within their own neighborhoods, which creates an environment ripe for racial antagonism [@trounstine_segregation_2016]. It is thus not simply the level of diversity or integration that matters for racial harmony and cooperation, but their patterns within a larger geographic framework [@trounstine_segregation_2016; @oliver_paradoxes_2010; @bharathi_public_2018]. 

Political polarization along racial lines may lead to decreased public spending and goods provision because groups may have different preferences, which can make compromise hard, and because groups may preceive a disutility in out-groups receiving public goods expenditure @baqir_public_1999. @einstein_divided_2012 found evidence that racial segregation predicts large political divisions at the metropolitan level and that these divisions can create a lack of willingness to compromise and collaborate on local policy problems. @trounstine_segregation_2016 finds similar results at the city level: that residential racial segregation is associated with both increased political division and decreased public spending. Thus, these authors suggest that it is the combination of homogenous neighborhoods within a much larger, diverse geographic area that leads to increased political polarization and reduced public goods spending in local governments. 

More recently, some scholars have called this hypothesis and its importance into question. For example, @lee_ethnic_2018 finds evidence that larger inequalities within the political system favoring socially powerful groups, not local diversity patterns leading to decreased cooperation, may be a better explanation of failures in public goods provision in diverse areas. Other suggests that additional factors, such as income segregation, may be important confounding factors in public goods provision. @an_its_2018, for example, suggests that the more closely related income inequality is to racial inequality, the less investment is made in public goods, and that this interaciton was a better predictor of public goods spending patterns than measures of diversity. inequality and diversity jointly. A variety of evidence suggests that it is meaningful to consider the effects of income inequaltiy and diversity and segregation jointly [@an_its_2018; @massey_american_1993]. Given the active debate in the literature over the relaitonships between diversity, segregation, public spending, and other factors, it is increasingly important to re-examine previously reported findings as a means of robustness checks. 

# Replication

For the most part, results from Trounstine (2016) were successfully replicated. All regressions and tables were fully replicated in R. However, I was unable to successfully replicate Trounstine (2016)’s marginal effects analyses and margins plots using R. There does not yet appear to be a built-in R function to calculate marginal or predicted effects or to generate margins plots from the complicated multi-level models employed in the original paper, and creating such a function was outside of the scope of this analysis. Nevertheless, these results were successfully replicated in Stata. 

There was one interesting outcome from my attempt to replicate the original Stata code in R. Due to the differences in R and Stata in dealing with missing values, my first replication of analyses using the financial segregation dataset were slightly different than the results in Stata from the original paper. In order to exclude cities from her analysis with only one census tract, Trounstine conditions her regressions in Stata such that the value for the number of census tracts is greater than one. In Stata, this does not remove missing values, whereas in R, it does. Since this variable is used only as a conditional filter and not as a regression variable (and thus, the observations with missing values for number of census tracts are not dropped), Trounstine’s analysis includes 14 cities and 58 observations with missing values for census tracts in addition to cities with two or more census tracts. This is a potential oversight on the part of the author, and I would suggest also dropping observations with missing census tract data, or else imputing them. Nevertheless, dropping these values did not have much of an effect on the subsequent results. 


# Extension

One concern with the original analysis in @trounstine_segregation_2016 is the large amount of missing data values in her original datasets. Because both R and Stata drop any observations with missing values for any of the variables used in a regression, this can exlcude a large portion of the data from the analysis and potentially bias the results if the data is not missing completely at random. A large amount of data is missing in both of the main datasets used in the analyses of @trounstine_segregation_2016. The main model specification using the racial polarization dataset exludes `r (obs_rp - 91)` of the original  `r obs_rp` observations, or  %`r round(100*(obs_rp - 91)/obs_rp,2)` of the data. Additionally, the main model specification using the financial segregation data set excludes `r obs_fin_seg - 13742` of the original `r obs_fin_seg` observations, or %`r round(100*(obs_fin_seg - 13742)/ obs_fin_seg,2)` of observations from the original dataset. 

In an attempt to better deal with the problem of missing data in @trounstine_segregation_2016, I impute missing values in the original data using the mice package in R, which generates multivariate imputations using chained equations [@mice]. While there are a variety of different imputation methods that could have been employed, multiple imputation (such as the multiple multivariate imputations generated by mice) is desireable because instead of inputting a single value such as the mean for missing values, it instead uses the distribution of the available data to estimate multiple potential values for the missing data. As a result, multiple imputation helps to account for the uncertainty inherent in the imputation process and allows for the calculation of standard errors around estimaotrs. As a result, multiple imputation allows the researcher to more accurately assess the of uncertainty in the analysis in general. 

Before performing the multiple imputations on the datasets, I first examined the missing data for patterns. To better understand any potential patterns in missing data, I plotted the pattern of missingness for only and created a histogram showing the frequency of missing values for those variables with missing values in figure X1 for the racial polarization data and figure X2 for the financial segregation data. Looking at figure X1, the histogram shows that the variables for the largest vote split along racial lines and the variable indicating whether or not the election had candidates of more than one race had by far the largest percentages of missing data, missing %`r round(sum(is.na(rp$biggestsplit))/nrow(rp)*100,2)` and  %`r round(sum(is.na(rp$biracial))/nrow(rp)*100,2)`, respectively. It is important to note that the variable for the largest vote split along racial lines is the dependent variable in the regresison analysis, and thus, we are missing a large percentage of this key variable. From the plot on the right, we can see that approximately 42% of observations are complete (have no missing values). There seem to be a correspondence between missing a value for biggest split and missing biracial. There also seem to be about 2% of values for wich most of the variables are missing. However, most observations are not missing more than 2-3 values. 

### need to fix numbers below because this was from the whole fin_seg and not from the one filtered via the regression coefficients

In figure X2, we can similarly observe the trends for the financial segregation dataset. In this dataset, there is a very high proportion of missing variables for a number of variables. For example, there are a `r sum(is.na(fin_seg$H_citytract_NHW_i))` missing values for the segregation index, which is the main independent variable, or %`r round(sum(is.na(fin_seg$H_citytract_NHW_i))/nrow(fin_seg)*100,2)` of the data. In this dataset, there are also many more observations for which values are missing for multiple variables in comparison to the racial polarization dataset. In total, a mere XX% of observations are complete for all variables included in the main specification for the financial segregaion dataset. 

Because neither dataset seems to exhibit any clear patterns in the missing, data, it makes sense to proceed with the imputation. For the racial polarization dataset, I performed multiple imputations with 20 iterations using mice, while for the financial segregation dataset, I performed only 5 iterations due to the large size of the dataset and computing limitaitons. A non-stochastic imputation method, Classification and Regression Trees (CART), was used instead of the default for the imputation for both datasets because of an error with matrix inversion caused by the data that prevented the use of the default method, predictive mean matching. For the racial polarization dataset, I included all of the variables used in the analysis associated with the dataset and was able to impute all missing values. For the financial segregation dataset, however, I only imputed values for the main independent variable, the segregation index, and a few other variables, although all variables used in the analysis were included in the data subset input into the mice function. More of the data could not be imputed from the financial segregation dataset due to computing and time constraints for this project given the dataset's large size and proportion of missing values. 

## make sure to talk about the fact that still a large number of values missing for the imputed variables here


Before examining the results of Trounstine's model using the multiply imputed data, I first ran some diagnostic tests on the imputation results to make sure that everything ran as expected. First, I checked the convergence of the algorithm used within mice() by plotting the trace lines as a function of the number of iterations for each of the variables. Then, I visually inspected the distributions of the imputed data in comparison to the original data with density and strip plots. All of these checks suggested that the imputed values were within a plausible range of the data and that their distribution fit the underlying distribution of the data relatively well. The only cases in which there was some cause for concern were for some of the variables with very few missing values in the racial polarization dataset (such as the indicators for region). However, this is more or less to be expected given the small number of imputations performed in these cases. Thus, and especially because there are so few of these values in the actual imputed datasets, this was not a major concern. See figures X and X1 to see the density plots of the imputed values overlayed on the density plots of the original variables. The rest of the plots and results of the diagnostic tests discussed ehre are presented in the Appendix. 


Then, I use the imputed datasets to re-estimate the original models, pooling the results to final pooled regression coefficients and parameters. 



# Bibliography
